#ifndef __CONFIG_H
#define __CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#define CONFIG_PROTO_VERSION 0x01

#define CONFIG_DEFAULT_PART_PITCH 4
#define CONFIG_DEFAULT_FEED_SPEED 255
#define CONFIG_DEFAULT_DISPLAY_BRIGHTNESS 255
#define CONFIG_DEFAULT_MOTOR_DIRECTION 0
#define CONFIG_DEFAULT_MOTOR_SLOWDOWN_DELAY 50
#define CONFIG_DEFAULT_REMAINING_PARTS 0
#define CONFIG_DEFAULT_TOTAL_PARTS 0
#define CONFIG_DEFAULT_LOW_PARTS_WARN 0
#define CONFIG_DEFAULT_LONG_PARTS_ID "Not set"

#define CONFIG_ENABLE_WDT

#ifdef __cplusplus
}
#endif

#endif
